
<?php 
	//echo var_dump($block->getOrderAttributes());
?>

<style type="text/css">
	#grid-fields li{
		list-style: none;
		float: left;
	}
	#grid-fields li label{
		padding: 5px;
	}

</style>

<div id="gridContainer">
	<section id="grid-fields"></section>
	<section id="grid-wrapper" class="grid-wrapper"></section>
	<section id="grid-paginator" class="grid-wrapper"></section>
</div>

<script>
require(['magentoGrid'], function(mageGrid){
	mageGrid.init({
		gridService: "<?=$this->getUrl('SalesGrid/Orders/OrderList');?>",
		orderUrl: "<?=$this->getUrl('sales/order/view/order_id/#####');?>",
		gridAttribService: "<?=$this->getUrl('SalesGrid/Orders/GridFields');?>"
	});
});
</script>