
<?php 
	//echo var_dump($block->getOrderAttributes());
?>

<style type="text/css">
	#grid-fields li{
		list-style: none;
		float: left;
	}
	#grid-fields li label{
		padding: 5px;
	}
	.form-search, #showHide{
		display: inline-block; 
		padding-top: 5px;
		padding-bottom: 5px;
	}

	.form-search input{
	    height: 45px;
	    width: 330px;
	    font-size: 20px;
	}


</style>

<div id="gridContainer">
	<a href="javascript:void(0);" id="showHide">SHOW/HIDE GRID OPTIONS</a>
	<section id="grid-fields"></section>
	<div>Search</div>
	<section id="grid-wrapper" class="grid-wrapper"></section>
	<section id="grid-paginator" class="grid-wrapper"></section>
</div>

<script>
require(['magentoGrid'], function(mageGrid){
	mageGrid.init({
		gridService: "<?=$this->getUrl('SalesGrid/Orders/OrderList');?>",
		orderUrl: "<?=$this->getUrl('sales/order/view/order_id/#####');?>",
		gridAttribService: "<?=$this->getUrl('SalesGrid/Orders/GridFields');?>"
	});
});
</script>